ARGS:
  epochs: 500000
  batch_size: -1
  patience: 1000

MODEL:
  f_hid: 18
  depth: 6
  in_lb: '[0.,0.]'
  in_ub: '[5.,1.]'
  act: tanh
  seed: 42
  lr: 0.001
  
NS:
  nx: [100, 100]

IN_VAR_NAMES:
 [t, x]

OUT_VAR_NAMES:
 [S, I, psi, beta_s_i]

CUSTOM_CONSTS:
  sigma: 0.1
  gamma: 3.
  w0: 1.
  w1: 1.
  w2: 15.
  w3: 1.

CUSTOM_FUNCS:
  beta: 12*x
  exact: 0*x

CONDS:
  pde:
     eq_string: '- (d/dt) S - beta(vars) * S * I + sigma /2 * (d/dx)^2 S - 1/2/w0 * ( (d/dx)^2 psi * S + (d/dx) psi * (d/dx) S ), 
                 - (d/dt) psi + sigma /2 * (d/dx)^2 psi - (w1* I **2 + w2* vars[:,1] * I + w3*(1-vars[:,1])**2 + ( (d/dx) psi )**2 ),
                   (d/dx) beta_s_i - beta(vars) * S * I ,
                   (d/dx) I '
     right_side: 0*vars[:,0], 0*vars[:,0], 0*vars[:,0], 0*vars[:,0]
     point_area: '[[tmin, tmax], [xmin, xmax]]'
     N: 1e4
  integral_border:
     eq_string: beta_s_i
     right_side: 0*vars[:,0]
     point_area: '[[tmin, tmax],[xmin, xmin]]'
     N: 1e2
  ode:
     eq_string: '- (d/dt) I + beta_s_i - gamma * I '
     right_side: 0*vars[:,0]
     point_area: '[[tmin, tmax],[xmax, xmax]]'
     N: 1e2
  initial:
     eq_string: S , I
     right_side: 0*vars[:,0] + 0.9 , 0*vars[:,0] + 0.1
     point_area: '[[tmin, tmin],[xmin, xmax]]'
     N: 1e2
  terminal:
     eq_string: psi
     right_side: 0*vars[:,0]
     point_area: '[[tmax, tmax],[xmin, xmax]]'
     N: 1e2

