ARGS:
  epochs: 5000
  batch_size: -1
  patience: 1000

MODEL:
  f_hid: 20
  depth: 5
  in_lb: '[0.,0.]'
  in_ub: '[1.,1.]'
  act: tanh
  seed: 42
  lr: 0.001
  
NS:
  nx: [100, 100]

IN_VAR_NAMES:
 [t, x]

OUT_VAR_NAMES:
 [u]

CUSTOM_CONSTS:
  alpha: 3.

CUSTOM_FUNCS:
  f: 1.+ x*0
  exact: x

CONDS:
  pde:
     eq_string: (d/dx) u , (d/dt) u
     right_side: f(_x), 0*_x[:,0]
     point_area: '[[tmin, tmax], [xmin, xmax]]'
     N: 1e4
  border1:
     eq_string: u
     right_side: exact(_x)
     point_area: '[[tmin, tmax],[xmin, xmin]]'
     N: 1e2
  border2:
     eq_string: u
     right_side: exact(_x)
     point_area: '[[tmin, tmax],[xmax, xmax]]'
     N: 1e2
  border3:
     eq_string: u
     right_side: exact(_x)
     point_area: '[[tmin, tmin],[xmin, xmax]]'
     N: 1e2
  border4:
     eq_string: u
     right_side: exact(_x)
     point_area: '[[tmax, tmax],[xmin, xmax]]'
     N: 1e2

