ARGS:
  epochs: 50000
  batch_size: -1
  patience: 1000

MODEL:
  f_hid: 20
  depth: 5
  in_lb: '[0.,0.,0.]'
  in_ub: '[1.,1.,1.]'
  act: tanh
  seed: 42
  lr: 0.0001
  
NS:
  nx: [20, 20, 20]

IN_VAR_NAMES:
 [t, x, y]

OUT_VAR_NAMES:
 [S, I, R, psi_S,psi_I,psi_R]

CUSTOM_CONSTS:
  gamma: 0.12
  beta: 0.34
  sigma: 0.02
  c: 0.01
  eta_S: 0.00005
  eta_I: 0.00005
  eta_R: 0.00005
  alpha_S: 1
  alpha_I: 10
  alpha_R: 1

CUSTOM_FUNCS:
  exact: 1*x #tf.math.exp
    
CONDS:
  pde:
     eq_string: '(d/dt) S - 1/alpha_S*( (d/dx) S * (d/dx) psi_S + S * ( (d/dx)^2 psi_S + (d/dy)^2 psi_S ) + (d/dy) S * (d/dy) psi_S ) + beta* S * I - eta_S *( (d/dx)^2 S + (d/dy)^2 S ),
                 (d/dt) I - 1/alpha_I*( (d/dx) I * (d/dx) psi_I + I * ( (d/dx)^2 psi_I + (d/dy)^2 psi_I ) + (d/dy) I * (d/dy) psi_I ) - beta* S * I + gamma* I - eta_I *( (d/dx)^2 I + (d/dy)^2 I ),
                 (d/dt) R - 1/alpha_R*( (d/dx) R * (d/dx) psi_R + R * ( (d/dx)^2 psi_R + (d/dy)^2 psi_R ) + (d/dy) R * (d/dy) psi_R ) - gamma* I - eta_R *( (d/dx)^2 R + (d/dy)^2 R ),
                 (d/dt) psi_S - alpha_S/2 * (( (d/dx) S )**2 + ( (d/dy) S )**2) + eta_S * ( (d/dx)^2 psi_S + (d/dy)^2 psi_S ) + c*( S + I + R ) + beta*( psi_I - psi_S )* I ,
                 (d/dt) psi_I - alpha_I/2 * (( (d/dx) I )**2 + ( (d/dy) I )**2) + eta_I * ( (d/dx)^2 psi_I + (d/dy)^2 psi_I ) + c*( S + I + R ) + beta*( psi_I - psi_S )* S + gamma*( psi_R - psi_I ),
                 (d/dt) psi_R - alpha_R/2 * (( (d/dx) R )**2 + ( (d/dy) R )**2) + eta_R * ( (d/dx)^2 psi_R + (d/dy)^2 psi_R ) + c*( S + I + R )
                 '
     right_side: 0*_x[:,0], 0*_x[:,0], 0*_x[:,0], 0*_x[:,0], 0*_x[:,0], 0*_x[:,0]
     point_area: '[[tmin, tmax], [xmin, xmax], [ymin, ymax]]'
     N: 5e3
  initial:
     eq_string: S , I , R
     right_side: 0.6*tf.math.exp(-10*((_x[:,1]-0.5)**2 +(_x[:,2]-0.5)**2)) ,0.6*tf.math.exp(-35*((_x[:,1]-0.6)**2 +(_x[:,2]-0.6)**2)), 0*_x[:,0]
     point_area: '[[tmin, tmin],[xmin, xmax], [ymin,ymax]]'
     N: 1e2
  terminal:
     eq_string: psi_S , psi_I - I , psi_R
     right_side: 0*_x[:,0], 0*_x[:,0], 0*_x[:,0]
     point_area: '[[tmax, tmax],[xmin, xmax],[ymin,ymax]]'
     N: 1e2
  border1:
     eq_string: S , I , R , psi_S , psi_I , psi_R
     right_side: 0*_x[:,0],0*_x[:,0],0*_x[:,0],0*_x[:,0],0*_x[:,0],0*_x[:,0]
     point_area: '[[tmin, tmax],[xmin, xmax],[ymin,ymin]]'
     N: 1e2
  border2:
     eq_string: S , I , R , psi_S , psi_I , psi_R
     right_side: 0*_x[:,0],0*_x[:,0],0*_x[:,0],0*_x[:,0],0*_x[:,0],0*_x[:,0]
     point_area: '[[tmin, tmax],[xmin, xmax],[ymax,ymax]]'
     N: 1e2
  border3:
     eq_string: S , I , R , psi_S , psi_I , psi_R
     right_side: 0*_x[:,0],0*_x[:,0],0*_x[:,0],0*_x[:,0],0*_x[:,0],0*_x[:,0]
     point_area: '[[tmin, tmax],[xmin, xmin],[ymin,ymax]]'
     N: 1e2
  border4:
     eq_string: S , I , R , psi_S , psi_I , psi_R
     right_side: 0*_x[:,0],0*_x[:,0],0*_x[:,0],0*_x[:,0],0*_x[:,0],0*_x[:,0]
     point_area: '[[tmin, tmax],[xmax, xmax],[ymin,ymax]]'
     N: 1e2

